# MAKE SURE ANY CHANGES YOU MAKE HERE IS ALSO APPLIED TO THE APPLICATION.YML IN TESTS
graphql:
  packages:
    - "com.leftindust.mockingbird.graphql"
    - "java.util.UUID"
  federation:
    enabled: true
spring:
  main:
    web-application-type: reactive
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  liquibase:
    change-log: classpath:dbchangelog.xml
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/mediq
    username: mediq
    password: mediq
# MAKE SURE ANY CHANGES YOU MAKE HERE IS ALSO APPLIED TO THE APPLICATION.YML IN TESTS