name: Integration Tests

on: [ push, workflow_dispatch]

jobs:
  Mockingbird Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gladio Integration Tests
        run: docker-compose -f mockingbird.test.docker-compose.yml up --force-recreate --build --abort-on-container-exit
  Gladio Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gladio Integration Tests
        run: docker-compose -f gladio.test.docker-compose.yml up --force-recreate --build --abort-on-container-exit
  Condor Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gladio Integration Tests
        run: docker-compose -f condor.test.docker-compose.yml up --force-recreate --build --abort-on-container-exit

