name: Integration Tests

on: [ push, workflow_dispatch ]

jobs:
  Mockingbird_Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            ls --recursive
            echo $DEV_ENV_FILE >> src/main/resources/serviceAccountKey.json
            docker-compose -f mockingbird.test.docker-compose.yml up --force-recreate --build --abort-on-container-exit
        shell: bash
        env:
            DEV_ENV_FILE : ${{secrets.SERVICE_ACCOUNT_KEY}}
