# This is a basic workflow to help you get started with Actions

name: Tests

on: [push, workflow_dispatch]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Mockingbird_Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
            echo $DEV_ENV_FILE >> mockingbird/src/main/resources/serviceAccountKey.json
        shell: bash
        env:
            DEV_ENV_FILE : ${{secrets.SERVICE_ACCOUNT_KEY}}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build with Gradle
        run: ./gradlew mockingbird:build
